# Topics centralized here. Edit directly to add/remove.

TOPICS = [
    "Business formation (LLC/DBA, Secretary of State filings)",
    "General business license / local tax receipt",
    "Industry licenses (food service, salon, contractor, childcare, auto dealer)",
    "Specialty permits (signage, sidewalk café, outdoor seating, pop-ups)",
    "Sales & use tax registration and filing",
    "Employer setup (withholding, unemployment insurance, worker's compensation)",
    "Home-based business rules",
    "Procurement/vendor registration & bidding",
    "Inspections (health, fire, building) and renewals",

    "Building/alteration permits; plan review",
    "Mechanical/electrical/plumbing permits",
    "Occupancy and fire safety certificates",
    "Demolition, grading, excavation",
    "Historic preservation approvals",
    "Short-term rental permits",
    "Contractor licensing/verification",
    "Code enforcement, stop-work orders, appeals",

    "Zoning lookups, variances, conditional use",
    "Setbacks, lot splits, subdivisions",
    "Easements & right-of-way questions",
    "Property records, deeds, plats",
    "Assessments and property tax appeals",
    "Vacant/abandoned properties, nuisance abatement",
    "HOA vs. city jurisdiction guidance (informational)"

    "Tree permits (remove/prune in right-of-way)",
    "Neighbor disputes (property damage, encroachment, fences)",
    "Noise, trash, pests, overgrowth complaints",
    "Graffiti, abandoned vehicles",
    "Animal nuisances",

    "Street/sidewalk closures for construction or events",
    "Driveway and curb-cut permits",
    "Utility cuts, trenching, restoration standards",
    "Oversize/overweight vehicle permits",
    "Potholes, streetlight outages, signage requests",
    "Snow/ice, leaf collection, street sweeping schedules",

    "Food truck/cart: commissary, health permit, route rules",
    "Restaurant permits, inspections, grade lookup",
    "Cottage food rules",
    "Farmers markets, temporary food events",
    "Septic/well permits; pool/spa permits",
    "Tattoo/body art and personal services licensing",
    "Smoking/vaping restrictions; youth access compliance",

    "Immunizations, clinics, WIC",
    "Medicaid/CHIP eligibility & enrollment",
    "SNAP/TANF and cash/family assistance (state administered)",
    "Mental health & substance use resources",
    "Aging & disability services, caregivers, adult protective services",
    "Homelessness services, shelters, supportive housing",
    "Domestic violence resources",

    "School enrollment, zoning/boundaries, transfers",
    "Special education (IDEA), evaluations, IEP process",
    "School meals, transportation eligibility",
    "Records (transcripts, diplomas), immunization requirements",
    "Truancy, homeschooling notice",
    "After-school and summer programs; daycare licensing lookups",

    "State colleges/universities admissions & residency",
    "State financial aid & scholarships",
    "Community college/CTE, apprenticeships",
    "Professional licensing boards (renewal, CE)",
    "Workforce centers, training grants",

    "Driver licenses/IDs, REAL ID, renewals, testing",
    "Vehicle title/registration, plates, emissions",
    "Disability placards",
    "Transit passes, paratransit eligibility",
    "Parking permits (residential, loading, construction)",
    "Tickets (parking/traffic) payment and appeals",
    "Towing and impound recovery",

    "Illicit discharge, spill reporting",
    "Stormwater utility fees & credits",
    "Floodplain permits, elevation certificates",
    "Wetlands/critical areas review",
    "Tree canopy/urban forestry programs",
    "Recycling/compost/hazardous waste",

    "Water/sewer start-stop, billing, leaks, backflow",
    "Solid waste service, bulky item pickup",
    "Power/gas start-stop (where public utility)",
    "311 service requests and status tracking",
    "Street address assignment",

    "Fire permits: alarms, sprinklers, hot work, hazardous storage",
    "Fire inspections and occupancy loads",
    "Community wildfire/smoke & defensible space rules",
    "Emergency alerts, evacuation zones, shelters",
    "Disaster debris pickup & rebuilding resources",
    "Police reports (how to file/obtain), incident records",

    "Traffic, municipal, small claims filing",
    "Protection/restraining orders (process, forms)",
    "Jury duty",
    "Fines/fees payment plans",
    "Expungement & record sealing (state-specific)",
    "Notary commissions and apostilles",

    "Birth/death/marriage certificates",
    "Marriage licenses and civil unions",
    "Name change process",
    "Domestic partnership registration (where applicable)",
    "Public records/FOIA (state public records laws)",
    "Proof of residency letters (when available)",

    "Rental licensing and inspections",
    "Habitability/code complaints",
    "Fair housing & anti-discrimination enforcement",
    "Security deposit rules (state)",
    "Eviction diversion/mediation, rental assistance",
    "Short-term rental compliance & taxes",

    "State income tax filing, refunds (where applicable)",
    "Property tax billing, exemptions (homestead, veterans, seniors)",
    "Sales/use/lodging taxes; marketplace rules",
    "Local business taxes & renewals",
    "Payment plans and penalties",
    "Unclaimed property searches & claims",

    "Voter registration, deadlines, ID requirements",
    "Polling place/ballot drop box lookup",
    "Absentee/mail-in ballots",
    "Sample ballots, measures, nonpartisan voter guides",
    "Poll worker signup",

    "Facility rentals (parks, shelters, fields)",
    "Special event/film permits",
    "Youth/senior programs and scholarships",
    "Hunting/fishing licenses, state park passes",
    "Library cards, fines, room bookings",

    "Pet licensing, rabies/vaccine clinics",
    "Animal control, bites, dangerous dogs",
    "Livestock/urban agriculture permits (chickens, bees)",
    "Wildlife conflicts and rehab",
    "4-H/extension programs; farm permits & scales",

    # "Complaints to Attorney General or consumer office",
    # "Price gouging, scams, robocalls",
    # "Wage theft & minimum wage ordinances (local/state)",
    # "Human rights commissions (housing/employment/public accommodations)",

    # "Unemployment insurance claims and appeals",
    # "Paid family/medical leave (state programs)",
    # "Workplace safety (state OSHA where applicable)",
    # "Apprenticeship registration",

    # "Small business grants/loans; façade programs",
    # "Opportunity zones, tax abatements",
    # "Land bank properties",
    # "Main Street & BID contacts",

    # "ADA accommodations for facilities and programs",
    # "Language access & interpretation/translation",
    # "Accessible web/app services and alternative formats",
    # "Assistive technology loan programs",

    # "Which agency handles X?” routing",
    # "Eligibility screening (“Do I qualify?”)",
    # "Document checklists",
    # "Timelines/SLAs and fee calculators",
    # "How to appeal/renew/reinstate",
    # "Contact info, office hours, appointments",
    # "Boating & Waterways",
    # "Aviation & Drones",
    # "Broadband & Digital Equity",
    # "Residential Energy & Weatherization Programs",
    # "Weights & Measures (Scales & Fuel Pumps)",
    # "Cemeteries & Funeral/Burial Services",
    # "Corrections, Jails & Reentry Services",
    # "Child & Family Services (Child Support, Foster/Adoption)",
    # "Coastal Management & Beach Access",
    # "Housing Assistance Programs (Public Housing & Vouchers)",
    # "Military & Veterans Services",
    # "Open Data, GIS & Map Services",
    # "Government Jobs & Civil Service Exams",
    # "Insurance & Financial Regulation (State DOI)",
    # "Gaming, Charitable Gaming & Lotteries",
    # "For-Hire Transportation (Taxi/Limo/TNC)",
    # "Ethics, Lobbying & Campaign Finance Compliance",
    # "Elevators, Boilers & Amusement Ride Safety",
    # "Mining, Oil & Gas Permitting",
    # "Forestry & Timber Harvest Permits",
    # "Public Utilities Regulation (PUC/PSC Complaints & Rate Cases)",
    # "Water Rights, Irrigation & Dams",
    # "Immigrant & New Resident Services (Municipal ID, ESL, Legal Referrals)"
    
    # "Radiation Control & X-Ray Device Licensing",
    # "Pesticide Applicator Certification",
    # "Public Art & Murals Permitting",
    # "Arts & Cultural Grants",
    # "Air Quality Permits & Burn Bans",
    # "Off-Highway Vehicle (ATV/Snowmobile) Registration",
    # "State Trust Lands Leases & Easements",
    # "Aquaculture & Shellfish Harvest Permits",
    # "Scientific Collecting & Research Permits",
    # "Address Confidentiality Program (ACP)",
    # "Identity Theft Recovery & Data Breach Assistance",
    # "Manufactured/Mobile Home Titling & Park Protections",
    # "Property Tax Foreclosure Prevention & Redemption",
    # "UCC Liens & Searches",
    # "Surplus Property Sales & Auctions",
    # "Volunteer Background Checks & Clearances",
    # "Traffic Calming (Speed Humps) Requests",
    # "ADA Curb Ramp Requests",
    # "School Zone Safety & Crossing Guards",
    # "Water Conservation Rebates & Turf Replacement",
    # "Lead-Safe Housing & Abatement Programs",
    # "Asbestos/Demolition Notification & Clearance",
    # "EV & Charging Infrastructure Permits & Rebates",
    # "Community Choice Energy (CCA) Enrollment/Opt-Out",
    # "Film & TV Production Incentives",
    # "Sex Offender Registry & Community Notifications",
    # "Geologic Hazards & Seismic Retrofit Programs",
    # "State Archives & Historical Records Research",
    # "Water Well Drilling & Abandonment Permits",
    # "Invasive Species Boat Inspections & Decontamination",
    # "Graywater & Rainwater Harvesting Permits",
    # "Youth Employment Work Permits (Minor Work Certificates)",
    # "Residential Disabled Parking Zone Requests",
    # "Flood Map Changes (LOMA/LOMR) Assistance",
    # "Backcountry & Wilderness Permits (State Parks)"
    # "Wildlife Depredation Permits for Crop Damage",
    # "Farm Vehicle Registration (Farm Plates) & Fuel Tax Exemptions",
    # "Carcass Disposal & Deadstock Rendering Rules",
    # "Soil & Water Conservation District Cost-Share Programs",
    # "Commercial Feed Manufacturer/Distributor Licensing",
    # "Nursery Stock Grower/Dealer Licensing",
    # "Seed Certification & Crop Inspection",
    # "Fertilizer & Soil Amendment Registration",
    # "Homeowner Rehabilitation & Emergency Repair Programs",
    # "Illegal Advertising Sign/Posters Removal (Public Right-of-Way)",
    # "Unpermitted Construction Work Complaints",
    # "Means of Egress/Exit Blockage Complaints",
    # "Emergency Building Condemnation & Unsafe Structure Abatement",
    # "Illegal Demolition & After-Hours Work Complaints",
    # "Industrial Wastewater Pretreatment & Discharge Permits/Violations",
    # "Air Quality Nuisance Complaints (Odor/Smoke/Dust)",
    # "Drinking Water Quality Complaints & Boil Water Notices",
    # "Public Urination/Defecation Complaints & Sanitation Cleanup"
]

